spring:
  main:
    web-application-type: none
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-other: true

    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test;Mode=Oracle
      username: sa
      password:
